### ISSUE TITLE
Instruction to Add to Laravel 5.2

### ISSUE THREAD

**Issue by dkpinn** [lokielse/laravel-admin-generator#4]
I have looked at the Admin-LTE and it definately looks inviting.

I have already setup a website and would like to started using the Admin LTE. How would one go about setting it up on a site that has already been created? What would need to be changed? Would we change the compose.json file?

**Comment by lokielse** [comment]
Hi @dkpinn , The package `laravel-admin-generator` is just another generator for Laravel, which dose two things
1. Generate a start up backbone with Admin-LTE or SB-Admin
2. Generate entities base on your business

Admin-LTE indeed looks inviting, while `laravel-admin-generator` just copy its js,css files to the right destinations automaticlly

There an instruction about how to use the package: https://github.com/lokielse/laravel-admin-generator/tree/master/docs

P.S. I used to create many admin sites, and I found that I always do the same things which waste much time. That is the reason I create this generator.
