### ISSUE TITLE
How to install? artisan not found.

### ISSUE THREAD

**Issue by sree541** [lokielse/laravel-admin-generator#7]
artisan command not working after downloading the project.
`php artisan admin:entity:new post admin-demo`

**Comment by danoetz** [comment]
Same problem here

**Comment by kamleshwebtech** [comment]
Getting issue during installation by composer:

composer require lokielse/laravel-admin-generator
Using version ^2.0 for lokielse/laravel-admin-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package lokielse/laravel-admin-generator No version set (parsed as 1.0.0) is satisfiable by lokielse/laravel-admin-generator[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by lokielse** [comment]
This repo is deprecated. You can use: https://github.com/InfyOmLabs/laravel-generator
